### ISSUE TITLE
fail to upload

### ISSUE THREAD

**Issue by r8b7xy** [imgbi/imgbi-client#4]
I can't upload images with name pattern I've created for my screenshots.

```
┌─[r8b7xy@arch]-[~/shots]-[Wed 17 Jun 22:29]
└─[i] imgbi-client -i desktop-2015-06-17-17:46:19.png
ERROR: -i expects a file. Use `imgbi-client -i FILE`
```

and when I change the name it prints util.print lines.

```
┌─[r8b7xy@arch]-[~/shots]-[Wed 17 Jun 22:34]
└─[i] imgbi-client -i file.png
util.print: Use console.log instead
https://img.bi/#/xxx
util.print: Use console.log instead
https://img.bi/#/rm/xxx
```

**Comment by komachi** [comment]
First is not the issue with the client. You need to add quotation marks to filename because it contain `:`.

Second issue should be fixed in 0.0.6.
